In [2]:
import numpy as np

In [16]:
#single values are scalar
scalar= np.array(5)
print(scalar)
scalar.shape
x=scalar+3
print(x)

5
8


numpy.int64

In [41]:
# vector can be 1 dimention values in form of single row or column
vector = np.array([1,2,3])
print(vector)
vector.shape

[1 2 3]


(3,)

In [18]:
x=vector[1]
print (x)

2


In [29]:
#matrices contaion only 2 dimentions and are represented in form of multiple rows and coulms
matrixs = np.array([[1,2,3],[4,5,6],[7,8,9]])
print( matrixs)
matrixs.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

In [49]:
#tensors are 3 dimentional or more than 3 dimentional and they are in form of multiple rows and columns
tensors = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[9,8,7],[6,5,4],[3,2,1]],[[2,4,6],[1,3,5],[8,7,9]]])
print (tensors)
tensors.shape
tensors[2][2][1]

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[9 8 7]
  [6 5 4]
  [3 2 1]]

 [[2 4 6]
  [1 3 5]
  [8 7 9]]]


7

In [53]:
#an example of 4d array also known as tensors
t=np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],[[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[18]]]])
print(t)
print("shape is",t.shape)
print("index = ",t[2][0][1][0])

[[[[ 1]
   [ 2]]

  [[ 3]
   [ 4]]

  [[ 5]
   [ 6]]]


 [[[ 7]
   [ 8]]

  [[ 9]
   [10]]

  [[11]
   [12]]]


 [[[13]
   [14]]

  [[15]
   [16]]

  [[17]
   [18]]]]
shape is (3, 3, 2, 1)
index =  14


In [66]:
#reshaping
print (vector)
print(vector.shape)
re=vector.reshape(1,3)
print(re)
print(re.shape)


[1 2 3]
(3,)
[[1 2 3]]
(1, 3)
