In [13]:
#performing bodmas operations on matrices
import numpy as np
a= np.array([[1,2,3],[4,2,4]])
print ("a=",a)
c=np.multiply(a,0.75)
print("C=",c)
b=np.array([[8,9,3],[3,4,2]])
print("B=",b)
d=np.add(b,10)
print("D=",d)
e=np.divide(c,d)
print("E=",e)


a= [[1 2 3]
 [4 2 4]]
C= [[0.75 1.5  2.25]
 [3.   1.5  3.  ]]
B= [[8 9 3]
 [3 4 2]]
D= [[18 19 13]
 [13 14 12]]
E= [[0.04166667 0.07894737 0.17307692]
 [0.23076923 0.10714286 0.25      ]]


In [21]:
#proper matrix multiplication making sure of dimentions and dot product of rows and coulmn
a= np.array([[1,2,3],[4,2,4]])
print ("a=",a)
c=np.multiply(a,0.75)
print("C=",c)
print ("shape of c",c.shape)
b=np.array([[8,9,3],[3,4,2],[3,4,1]])
print("B=",b)
d=np.add(b,10)
print("D=",d)
print("shape of d",d.shape)
e=np.matmul(c,d)
print("E=",e)
print("shape of e",e.shape)

a= [[1 2 3]
 [4 2 4]]
C= [[0.75 1.5  2.25]
 [3.   1.5  3.  ]]
shape of c (2, 3)
B= [[8 9 3]
 [3 4 2]
 [3 4 1]]
D= [[18 19 13]
 [13 14 12]
 [13 14 11]]
shape of d (3, 3)
E= [[ 62.25  66.75  52.5 ]
 [112.5  120.    90.  ]]
shape of e (2, 3)


In [22]:
#it does not work because of the mismatch of dimention of rows and coulmn 
f=np.matmul(d,c)
print(f)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)