In [40]:
#breaking a 1 dimentional list into 2 dimentional array
# find the minimum value in input_array and subtract that value from all the elements of input_array. Store the result in inputs_minus_min
# TODO: find the maximum value in inputs_minus_min and divide all of the values in inputs_minus_min by the maximum value.Store the results in inputs_div_max.

import numpy as np
def prepare_inputs(inputs):
    input_array=np.array(inputs).reshape(2,2)
    print ("value of input array=",input_array)
    b=input_array.min()
    print ("the minimum value in input array =",b)
    c=input_array-b
    print ("the value of input array after subtracting minimum value is=",c)
    inputs_minus_min=c
    print ("inputs_minus_min = ",inputs_minus_min)
    inputs_div_max= inputs_minus_min/inputs_minus_min.max()
    print("inputs_div_max=",inputs_div_max)
z=prepare_inputs(inputs=[-1,2,7,9])
print(z)



value of input array= [[-1  2]
 [ 7  9]]
the minimum value in input array = -1
the value of input array after subtracting minimum value is= [[ 0  3]
 [ 8 10]]
inputs_minus_min =  [[ 0  3]
 [ 8 10]]
inputs_div_max= [[0.  0.3]
 [0.8 1. ]]
None


In [34]:
# TODO: Check the shapes of the matrices m1 and m2.  m1 and m2 will be ndarray objects.Return False if the shapes cannot be used for matrix multiplication. You may not use a transpose pass
import numpy as np
def multiply_inputs(m1, m2):
    print("m1=",m1)
    print(m1.shape)
    print("m2=",m2)
    print(m2.shape)
    if(m1.shape[1] != m2.shape[0]):
        swap=m1
        m1=m2
        m2=swap
        print("m1",m1,"m2",m2)
        if(m1.shape[1] != m2.shape[0]):
            return False
        else:
            x=np.matmul(m1,m2)
            return x
    else:
        x=np.matmul(m1,m2)
        return x
       
y=multiply_inputs(m1=np.array([[1,2,3],[4,5,6]]),m2=np.array([[1],[2],[3],[4]]))
print("y=",y)



m1= [[1 2 3]
 [4 5 6]]
(2, 3)
m2= [[1]
 [2]
 [3]
 [4]]
(4, 1)
m1 [[1]
 [2]
 [3]
 [4]] m2 [[1 2 3]
 [4 5 6]]
y= False


In [33]:
# TODO: Check the shapes of the matrices m1 and m2.  m1 and m2 will be ndarray objects.Return False if the shapes cannot be used for matrix multiplication. You may not use a transpose pass
def multiply_inputs(m1, m2):
    print("m1=",m1)
    print(m1.shape)
    print("m2=",m2)
    print(m2.shape)
    if(m1.shape[1] != m2.shape[0]):
        swap=m1
        m1=m2
        m2=swap
        if(m1.shape[1] != m2.shape[0]):
            return False
        else:
            x=np.matmul(m1,m2)
            return x
    else:
            x=np.matmul(m1,m2)
            return x
y=multiply_inputs(m1=np.array([[1,2,3],[4,5,6]]),m2=np.array([[1],[2],[3]]))
print("y=",y)



m1= [[1 2 3]
 [4 5 6]]
(2, 3)
m2= [[1]
 [2]
 [3]]
(3, 1)
y= [[14]
 [32]]


In [31]:
# TODO: Check the shapes of the matrices m1 and m2.  m1 and m2 will be ndarray objects.Return False if the shapes cannot be used for matrix multiplication. You may not use a transpose pass
def multiply_inputs(m1, m2):
    print("m1=",m1)
    print(m1.shape)
    print("m2=",m2)
    print(m2.shape)
    if(m1.shape[1] != m2.shape[0]):
        swap=m1
        m1=m2
        m2=swap
        if(m1.shape[1] != m2.shape[0]):
            return False
        else:
            x=np.matmul(m1,m2)
            return x
y=multiply_inputs(m1=np.array([[1,2,3],[4,5,6]]),m2=np.array([[1,2]]))
print("y=",y)


m1= [[1 2 3]
 [4 5 6]]
(2, 3)
m2= [[1 2]]
(1, 2)
y= [[ 9 12 15]]


In [40]:
def find_mean(values):
    v=np.average(values)
    return v
w=find_mean(values=[1,3,4])
print("the mean of list values are=",w)




the mean of list values are= 2.6666666666666665
