In [6]:
#transposing a matrix and multiplying it (transposed because the dimention diddnt match transposting helps matching dimention in some cases)
import numpy as np
a=np.array([[1,2,3],[3,2,1],[4,5,6],[7,8,9]])
print ("a=",a)
print ("shape of a = ",a.shape)
b=np.array([[1,2,3],[4,3,2]])
print("b=",b)
print ("shape of b = ",b.shape)
d=b.T
print("d=",d)
print ("shape of d=",d.shape)
c=np.matmul(a,d)
print ("c=",c)
print ("shape of c =",c.shape)

a= [[1 2 3]
 [3 2 1]
 [4 5 6]
 [7 8 9]]
shape of a =  (4, 3)
b= [[1 2 3]
 [4 3 2]]
shape of b =  (2, 3)
d= [[1 4]
 [2 3]
 [3 2]]
shape of d= (3, 2)
c= [[14 16]
 [10 20]
 [32 43]
 [50 70]]
shape of c = (4, 2)


In [12]:
#changing the value of transposed resultant matrix
#when u change the value in a transposed matrix the value in the origmal matrix may change
e=a.T
print("e=",e)
e[0][0]=0
print("e = ",e)
print ("a=",a)

e= [[0 3 4 7]
 [2 2 5 8]
 [3 1 6 9]]
e =  [[0 3 4 7]
 [2 2 5 8]
 [3 1 6 9]]
a= [[0 2 3]
 [3 2 1]
 [4 5 6]
 [7 8 9]]


0
